name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          # You can specify these options if you need
          # rules: '.github/markdownlint/rules'  # Optional custom rule path
          # config: '.markdownlint.json'         # Optional config file
          # fix: false                           # Set to true to auto-fix issues
          # output: './lint-report.txt'          # Save issues to a file
          # ignore: 'CHANGELOG.md'               # Ignore specific files
          args: '**/*.md'                        # Lint all markdown files
